homepage:
    pattern:  /
    defaults: { _controller: WebsiteBundle:Default:index }
    
WebsiteBundle_login:
    pattern: /login
    defaults: { _controller: WebsiteBundle:Default:login }

WebsiteBundle_login_check:
    pattern: /login_check
    
homepage_cadastro:
    pattern: /cadastro.{_format}
    defaults: { _controller: WebsiteBundle:Usuario:cadastro, _format: html}
    requirements:
        _format: html|htm

homepage_cadastro_sucesso:
    pattern: /cadastro_sucesso.{_format}
    defaults: {_controller:WebsiteBundle:Usuario:sucesso, _format:html}
    requirements:
        _format: html