WebsiteBundle_homepage:
    pattern:  /
    defaults: { _controller: WebsiteBundle:Default:index }
    
WebsiteBundle_login:
    pattern: /login
    defaults: { _controller: WebsiteBundle:Default:login }

WebsiteBundle_login_check:
    pattern: /login_check
