homepage:
    pattern:  /
    defaults: { _controller: WebsiteBundle:Default:index }
    
login:
    pattern: /login
    defaults: { _controller: WebsiteBundle:Default:login }

login_check:
    pattern: /login_check
    
homepage_cadastro:
    pattern: /cadastro.{_format}
    defaults: { _controller: WebsiteBundle:Usuario:cadastro, _format: html}
    requirements:
        _format: html|htm

homepage_cadastro_sucesso:
    pattern: /cadastro_sucesso.{_format}
    defaults: {_controller:WebsiteBundle:Usuario:sucesso, _format:html}
    requirements:
        _format: html

contagem_usuarios:
    pattern: /usuarios/contagem.{_format}
    defaults: {_controller:WebsiteBundle:Usuario:getContagem }
    requirements:
         _format: html|htm|xml|json
         
validar_chave_usuario:
    pattern: /valida_cadastro/{token}
    defaults: {_controller: WebsiteBundle:Usuario:validaCadastro, token:null }
    requirements:
       _method: GET
    