# Estrutura das permissões de acesso
# ROLE_USER = Usuário visitante do site
# ROLE_SUPER_USER = Usuário do site, porém autenticado
# ROLE_ADMIN = Usuário que pode administrar o site
# ROLE_SUPER_ADMIN = Super administrador do site. Pode fazer de tudo.

security:
    role_hierarchy:
        ROLE_SUPER_USER:  ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_SUPER_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SUPER_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_providers:
            providers: [user_db]
        user_db:
            entity: {class: PHPReview\WebsiteBundle\Entity\Usuario, property: ds_email }   

    encoders:
        PHPReview\WebsiteBundle\Entity\Usuario:
            algorithm:  sha1
            iterations: 5000
            encode_as_base64: true

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                path:   /logout
                target: /
            #http_basic:
            #    realm: "Secured Demo Area"

    access_denied_url: /login
    access_control:
         - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/edicoes, roles: ROLE_USER }
         - { path: /admin, roles: ROLE_SUPER_USER } 
         #, requires_channel: https }
         #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
