<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Criação da tabela de estados.
 */
class Version20120515144213 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->connection->insert('estados',array('ds_estado'=>'Acre','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Alagoas','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Amapá','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Amazonas','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Bahia','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Ceará','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Distrito Federal','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Espírito Santo','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Goiás','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Maranhão','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Mato Grosso','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Mato Grosso do Sul','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Minas Gerais','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Pará','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Paríba','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Paraná','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Pernambuco','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Piauí','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Rio de Janeiro','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Rio Grande do Norte','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Rio Grande do Sul','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Rondônia','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Roraima','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Santa Catarina','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'São Paulo','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Sergipe','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'Tocantins','in_disponivel'=>1,'nacao'=>'BRA'));
        $this->connection->insert('estados',array('ds_estado'=>'- Outros Países','in_disponivel'=>1,'nacao'=>''));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->connection->delete('estados',array());

    }
}
