<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120704193204 extends AbstractMigration
{
    public function up(Schema $schema)
    {
       $this->connection->insert('tipochave',array('ds_tipo_chave'=>'Confirmar Cadastro'));
       $this->connection->insert('tipochave',array('ds_tipo_chave'=>'Recuperar Senha'));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->connection->delete('tipochave',array());

    }
}
