<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120613212720 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // Inserindo os dados da tabela de Nível Hierárquico
        $this->connection->insert('tipopublicacao',array('nome'=>'Revista','descricao'=>'Revistas de publicações periódicas','data_cadastro'=>date(\Datetime::ATOM),'login_cadastro'=>1,'ativo'=>1));
        $this->connection->insert('tipopublicacao',array('nome'=>'Edição Especial','descricao'=>'Edições especiais da revista PHP Review.','data_cadastro'=>date(\Datetime::ATOM),'login_cadastro'=>1,'ativo'=>1));
        $this->connection->insert('tipopublicacao',array('nome'=>'Livros','descricao'=>'Livros não gratuitos em formato PDF para disponibilização do usuário.','data_cadastro'=>date(\Datetime::ATOM),'login_cadastro'=>1,'ativo'=>1));
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->connection->delete('tipopublicacao',array());

    }
}
