<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20120515144213 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->connection->insert('estados',array('id_estado'=>0,'ds_estado'=>'Acre','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>1,'ds_estado'=>'Alagoas','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>2,'ds_estado'=>'Amapá','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>3,'ds_estado'=>'Amazonas','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>4,'ds_estado'=>'Bahia','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>5,'ds_estado'=>'Ceará','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>6,'ds_estado'=>'Distrito Federal','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>7,'ds_estado'=>'Espírito Santo','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>8,'ds_estado'=>'Goiás','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>9,'ds_estado'=>'Maranhão','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>10,'ds_estado'=>'Mato Grosso','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>11,'ds_estado'=>'Mato Grosso do Sul','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>12,'ds_estado'=>'Minas Gerais','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>13,'ds_estado'=>'Pará','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>14,'ds_estado'=>'Paríba','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>15,'ds_estado'=>'Paraná','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>16,'ds_estado'=>'Pernambuco','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>17,'ds_estado'=>'Piauí','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>18,'ds_estado'=>'Rio de Janeiro','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>19,'ds_estado'=>'Rio Grande do Norte','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>20,'ds_estado'=>'Rio Grande do Sul','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>21,'ds_estado'=>'Rondônia','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>22,'ds_estado'=>'Roraima','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>23,'ds_estado'=>'Santa Catarina','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>24,'ds_estado'=>'São Paulo','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>25,'ds_estado'=>'Sergipe','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>26,'ds_estado'=>'Tocantins','in_disponivel',1));
        $this->connection->insert('estados',array('id_estado'=>27,'ds_estado'=>'- Outros Países','in_disponivel',1));

    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->connection->delete('estados',array());

    }
}
