homepage:
    resource: PHPReview\AdminBundle\Controller\DefaultController
    type:     annotation

usuario: 
    resource: PHPReview\AdminBundle\Controller\UsuarioController
    type:     annotation