AdminBundle_homepage:
    pattern:  /
    defaults: { _controller: AdminBundle:Default:index }
    
AdminBundle_login:
    pattern: /login
    defaults: { _controller: AdminBundle:Default:login }

AdminBundle_login_check:
    pattern: /login_check

